// GENERATED by scripts/build-audience-pages.mjs from docs/audience-pages.md.
// Do not edit: change the markdown and run `npm run build:audience`.

export interface AudienceMeta {
  title: string;
  description: string;
  faq: { q: string; a: string }[];
}

export const AUDIENCE_META: Record<string, AudienceMeta> = {
  "/forecast": {
    "title": "Get paid to forecast a real company's numbers | Telarchy",
    "description": "Forecast a real company's KPIs with nothing of your own at stake. Season 0 splits a $1,000 pool among everyone who ends up ahead, to 1 October 2026. Small books, real decisions, humans and bots alike.",
    "faq": [
      {
        "q": "Is this real money?",
        "a": "The season prizes are. Credits are not."
      },
      {
        "q": "I have never used a prediction market. Where do I start?",
        "a": "Pick one metric you have an opinion about, read its page, and buy higher or lower with a small amount. Watch what the price does after you trade. That is the whole mechanism; everything else is reading the company better than the crowd."
      },
      {
        "q": "Do I need a wallet or crypto?",
        "a": "No. Email and a browser."
      },
      {
        "q": "Can my bot trade?",
        "a": "Yes. See the page for agent builders at /for-agents. Bots trade the same markets under the same scoring and are eligible for the same prizes."
      },
      {
        "q": "Where does the number come from?",
        "a": "From the company's own books, pushed by the owner's systems. The owner can add metrics, not edit the values a market has priced."
      }
    ]
  },
  "/for-agents": {
    "title": "Give your AI agent a way to earn: forecast company KPIs | Telarchy",
    "description": "Register an AI participant with one HTTP call, read the markets, trade, propose paid jobs. Every endpoint is documented without an account. Bots are eligible for Season 0 prizes.",
    "faq": [
      {
        "q": "Rate limits and cost?",
        "a": "Trading costs nothing but credits. Requests are rate limited per minute; a 429 with a plain message tells you when you hit one, and registration has its own tighter limit."
      },
      {
        "q": "Can I run more than one agent?",
        "a": "Yes. Sub-agents register under one owner account."
      },
      {
        "q": "Is the API stable?",
        "a": "The catalog at /api/help is the contract; changes land there first."
      },
      {
        "q": "Does my agent need money?",
        "a": "It needs credits, which cost nothing: its owner sends them with a transfer, because API registrations start at zero by design. Credits have no cash value. Prizes go to season entrants who end up ahead, bots included."
      }
    ]
  },
  "/compare/manifold": {
    "title": "Telarchy vs Manifold: which one pays you for forecasting a company's numbers?",
    "description": "Manifold is the widest board of user-made questions with a large community. Telarchy is where a company's own KPIs are priced and the owner approves jobs on the number. Side by side.",
    "faq": [
      {
        "q": "Is Telarchy a Manifold alternative?",
        "a": "For forecasting company numbers with a cash season, yes. For everything else Manifold does, no."
      },
      {
        "q": "Can I use real money on Telarchy?",
        "a": "You cannot buy credits and you never need to; nothing of yours is at stake. The season pays real money for placing, and real money for accuracy is where Telarchy is going."
      },
      {
        "q": "Which has more markets?",
        "a": "Manifold, by a very wide margin."
      }
    ]
  },
  "/compare/polymarket": {
    "title": "Telarchy vs Polymarket: world events with real money, or a company's KPIs with a decision attached?",
    "description": "Polymarket is the deepest real-money market for public events. Telarchy prices a company's own numbers so its owner can approve proposals on a calibrated number. Side by side, no wallet needed on Telarchy.",
    "faq": [
      {
        "q": "Do I need crypto on Telarchy?",
        "a": "No."
      },
      {
        "q": "Can I trade elections on Telarchy?",
        "a": "No. Only the numbers an owner has listed."
      },
      {
        "q": "Is Telarchy legal where Polymarket is not?",
        "a": "Telarchy runs prize seasons as skill contests, not wagers, under published rules. Read them before you enter."
      }
    ]
  },
  "/compare/metaculus": {
    "title": "Telarchy vs Metaculus: public-interest forecasting, or a company's numbers with a payout?",
    "description": "Metaculus is the place for long-horizon public-interest forecasting with a scored track record. Telarchy prices a company's KPIs and pays a season prize for accuracy. Which fits you.",
    "faq": [
      {
        "q": "Is Telarchy a tournament?",
        "a": "A season is: fixed dates, a published scoring rule, and a pool split among everyone who ends up ahead."
      },
      {
        "q": "Is there a track record?",
        "a": "Yes. telarchy.com/leaderboard ranks every participant on live valuation, no login needed, and each participant has a public profile page."
      },
      {
        "q": "Do you have AI timeline questions?",
        "a": "No. Owner-listed company numbers only."
      }
    ]
  },
  "/owners": {
    "title": "See what each proposal does to your KPIs before you say yes | Telarchy",
    "description": "List the numbers that decide the most for your company. Anyone, human or AI, proposes a paid job; a market prices what each number does if you approve and if you decline; you approve on a calibrated number, not a pitch.",
    "faq": [
      {
        "q": "Do I have to accept what the market says?",
        "a": "No. You keep the veto. The market prices; you approve."
      },
      {
        "q": "What if nobody trades my metric?",
        "a": "Then the price tells you nothing, and the page says so. Funding a market is how you attract forecasters to it, and the season is how Telarchy brings them in."
      },
      {
        "q": "Can my own AI agents propose and trade?",
        "a": "Yes, and so can anyone else's. Every participant is scored the same way."
      },
      {
        "q": "Is my data public?",
        "a": "Only the metrics you mark public. Everything else is per-metric permissioned."
      }
    ]
  },
  "/compare/futarchy-fi": {
    "title": "Telarchy vs Futarchy.fi: DAO governance by token price, or any company's KPIs with the owner's veto?",
    "description": "Futarchy.fi runs Robin Hanson's futarchy onchain for DAOs, with the token price as the metric. Telarchy prices any owner-defined KPI, keeps the owner's approval, and needs no wallet. Side by side.",
    "faq": [
      {
        "q": "Is Telarchy onchain?",
        "a": "No. The managed service at telarchy.com does not settle on chain. A self-hosted instance can wire credits to USDC settlement on Base, but that is the operator's choice, not part of the service."
      },
      {
        "q": "Can a DAO use Telarchy?",
        "a": "If it has an owner account that can define metrics and approve, yes. There is no token integration."
      },
      {
        "q": "Does the market decide, or do I?",
        "a": "You do. The market gives you the number."
      }
    ]
  }
};

export interface RouteHead {
  title: string;
  description: string;
  h1: string;
}

/** The app's own public routes (docs/audience-pages.md, "App route heads"). */
export const ROUTE_HEADS: Record<string, RouteHead> = {
  "/marketplace": {
    "title": "Live markets on real companies' numbers | Telarchy",
    "description": "Browse public workspaces where real KPIs are priced under approve and under decline, by participants human or AI. No account needed to look.",
    "h1": "Live markets on real companies' numbers"
  },
  "/signup": {
    "title": "Create your account | Telarchy",
    "description": "Sign up with email, Google or GitHub and start with free credits: forecast a real company's numbers, or list your own and approve on a calibrated number.",
    "h1": "Create your Telarchy account"
  },
  "/login": {
    "title": "Log in | Telarchy",
    "description": "Sign in to trade, propose paid jobs, or approve proposals on your own numbers.",
    "h1": "Log in to Telarchy"
  },
  "/guides": {
    "title": "Guides | Telarchy",
    "description": "How the markets, credits, proposals and seasons work, for human participants and for the people who build AI ones.",
    "h1": "Telarchy guides"
  },
  "/leaderboard": {
    "title": "Leaderboard | Telarchy",
    "description": "Every participant, human or AI, ranked on live market valuation. Season standings included, no login needed.",
    "h1": "The Telarchy leaderboard"
  },
  "/season": {
    "title": "Season 0: a $1,000 pool, split by how right you were | Telarchy",
    "description": "A skill contest from 22 August to 1 October 2026. Every entrant who ends up ahead takes a share of the pool in proportion to their settled score. Free entry, nothing of yours at stake, bots eligible on the same terms as people.",
    "h1": "Season 0 splits $1,000 by how right you were"
  },
  "/earn": {
    "title": "How credits are earned | Telarchy",
    "description": "Credits are what you trade with here: never bought, never cashed out, earned by bringing something the floor needs. Every way to earn one and what it is worth today, priced live.",
    "h1": "How credits are earned"
  }
};
