/**
 * First-boot admin creation and startup config validation.
 *
 * On first start (no users in DB), creates an initial admin account using
 * INITIAL_ADMIN_EMAIL + INITIAL_ADMIN_PASSWORD. If INITIAL_ADMIN_PASSWORD
 * is not set, one is auto-generated and printed to stdout. This mirrors
 * GitLab's first-boot root admin pattern.
 *
 * On every boot, also elevates any existing user whose email matches
 * INITIAL_ADMIN_EMAIL to platform_admin=true. Covers the case where a
 * user was created before INITIAL_ADMIN_EMAIL was set in the env, or
 * where the operator imported/migrated an existing DB.
 */
import { randomBytes, randomUUID } from 'crypto';
import { eq } from 'drizzle-orm';
import { db } from '../db/client';
import { agentApiKeys, agents, authAccount, authUser } from '../db/schema';
import { hashKey } from '../middleware/auth';
import { applyCredits, PLATFORM_SCOPE } from '../services/credits';
import { provisionWorkspace } from './participants';
import { SIGNUP_CREDITS, toUnits } from './validation';

async function hashAuthPassword(password: string): Promise<string> {
  const { hashPassword } = await import('better-auth/crypto');
  return hashPassword(password);
}

/**
 * Validate startup config and emit warnings. Call before accepting requests.
 */
export function validateStartupConfig(): void {
  const hasGoogle = process.env.GOOGLE_CLIENT_ID || process.env.GOOGLE_CLIENT_SECRET;
  const hasGithub = process.env.GITHUB_CLIENT_ID || process.env.GITHUB_CLIENT_SECRET;
  const hasBetterAuthUrl = process.env.BETTER_AUTH_URL?.trim();

  if ((hasGoogle || hasGithub) && !hasBetterAuthUrl) {
    console.warn(
      '\n[WARN] OAuth provider credentials are set but BETTER_AUTH_URL is not.\n' +
        '       OAuth redirect URIs will be wrong on custom domains.\n' +
        '       Set BETTER_AUTH_URL=https://your-domain.com\n' +
        '       Callback URLs to register in your OAuth app:\n' +
        '         Google:  {BETTER_AUTH_URL}/api/auth/callback/google\n' +
        '         GitHub:  {BETTER_AUTH_URL}/api/auth/callback/github\n',
    );
  }
}

/**
 * Promote the user whose email matches INITIAL_ADMIN_EMAIL to platform_admin.
 * Idempotent: skips when the env var is unset, the user does not exist, or
 * the user is already a platform admin.
 */
export async function ensureInitialAdminElevated(): Promise<void> {
  const rawEmail = process.env.INITIAL_ADMIN_EMAIL?.trim();
  if (!rawEmail) return;
  const email = rawEmail.toLowerCase();

  const [user] = await db.select({ id: authUser.id }).from(authUser).where(eq(authUser.email, email));
  if (!user) return;

  const [agent] = await db
    .select({ id: agents.id, platformAdmin: agents.platformAdmin })
    .from(agents)
    .where(eq(agents.authUserId, user.id));
  if (!agent || agent.platformAdmin === true) return;

  await db.update(agents).set({ platformAdmin: true }).where(eq(agents.id, agent.id));
  console.log(`[bootstrap] Elevated ${email} to platform admin (matched INITIAL_ADMIN_EMAIL).`);
}

/**
 * Create the initial admin account on first boot.
 * No-op if any user already exists in the database, except that it still
 * promotes a user matching INITIAL_ADMIN_EMAIL to platform_admin so that
 * env-driven admin assignment works on existing databases too.
 */
export async function runBootstrap(): Promise<void> {
  validateStartupConfig();

  const [existingUser] = await db.select({ id: authUser.id }).from(authUser).limit(1);
  if (existingUser) {
    await ensureInitialAdminElevated();
    return;
  }

  const email = (process.env.INITIAL_ADMIN_EMAIL || 'admin@localhost').trim().toLowerCase();
  const providedPassword = process.env.INITIAL_ADMIN_PASSWORD?.trim();
  const autoGenerated = !providedPassword;
  const password = providedPassword || randomBytes(12).toString('base64url');

  const userId = randomBytes(16).toString('hex');
  const agentId = userId;
  const hashedPassword = await hashAuthPassword(password);
  const agentKeyRaw = randomBytes(32).toString('hex');
  const agentKeyHash = hashKey(agentKeyRaw);

  await db.transaction(async tx => {
    await tx.insert(authUser).values({
      id: userId,
      name: 'Admin',
      email,
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // BetterAuth credential account for email+password sign-in
    await tx.insert(authAccount).values({
      id: randomBytes(16).toString('hex'),
      accountId: userId,
      providerId: 'credential',
      userId,
      password: hashedPassword,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // Zero at insert, granted through the ledger: every credit that exists
    // has a row saying where it came from (docs/market-integrity.md).
    await tx.insert(agents).values({
      id: agentId,
      apiKeyHash: agentKeyHash,
      authUserId: userId,
      platformAdmin: true,
      balance: 0,
      createdAt: new Date(),
      approvedAt: new Date(),
    });
    await applyCredits(tx, {
      agentId,
      workspaceId: PLATFORM_SCOPE,
      deltaUnits: toUnits(SIGNUP_CREDITS),
      reason: 'signup_grant',
    });

    const wsId = randomUUID();
    await provisionWorkspace(tx, {
      wsId,
      name: 'My Workspace',
      createdBy: userId,
      ownerAgentId: agentId,
    });
    await tx.insert(agentApiKeys).values({
      hash: agentKeyHash,
      keyId: randomUUID(),
      agentId,
      workspaceId: wsId,
      scopes: ['*'],
    });
  });

  const line = '═'.repeat(62);
  const pad = (s: string) => s.padEnd(60);
  const rows = [
    `╔${line}╗`,
    `║  ${pad('TELARCHY — FIRST BOOT COMPLETE')}  ║`,
    `╠${line}╣`,
    `║  ${pad(`Email:    ${email}`)}  ║`,
    ...(autoGenerated
      ? [
          `║  ${pad(`Password: ${password}`)}  ║`,
          `║  ${pad('')}  ║`,
          `║  ${pad('Auto-generated password — save it now.')}  ║`,
          `║  ${pad('Set INITIAL_ADMIN_PASSWORD in your env to')}  ║`,
          `║  ${pad('pre-configure it on future installs.')}  ║`,
        ]
      : [`║  ${pad('Password: (set via INITIAL_ADMIN_PASSWORD)')}  ║`]),
    `╚${line}╝`,
  ];
  console.log('\n' + rows.join('\n') + '\n');
}
