/**
 * First-boot admin creation and startup config validation.
 *
 * On first start (no users in DB), creates an initial admin account using
 * INITIAL_ADMIN_EMAIL + INITIAL_ADMIN_PASSWORD. If INITIAL_ADMIN_PASSWORD
 * is not set, one is auto-generated and printed to stdout. This mirrors
 * GitLab's first-boot root admin pattern.
 *
 * Idempotent: does nothing once any user row exists.
 */
import { randomBytes } from 'crypto';
import { db } from '../db/client';
import { authUser, authAccount, appUsers, agents, agentApiKeys } from '../db/schema';
import { hashKey } from '../middleware/auth';

async function hashAuthPassword(password: string): Promise<string> {
  const { hashPassword } = await import('better-auth/crypto');
  return hashPassword(password);
}

/**
 * Validate startup config and emit warnings. Call before accepting requests.
 */
export function validateStartupConfig(): void {
  const hasGoogle = process.env.GOOGLE_CLIENT_ID || process.env.GOOGLE_CLIENT_SECRET;
  const hasGithub = process.env.GITHUB_CLIENT_ID || process.env.GITHUB_CLIENT_SECRET;
  const hasBetterAuthUrl = process.env.BETTER_AUTH_URL?.trim();

  if ((hasGoogle || hasGithub) && !hasBetterAuthUrl) {
    console.warn(
      '\n[WARN] OAuth provider credentials are set but BETTER_AUTH_URL is not.\n' +
      '       OAuth redirect URIs will be wrong on custom domains.\n' +
      '       Set BETTER_AUTH_URL=https://your-domain.com\n' +
      '       Callback URLs to register in your OAuth app:\n' +
      '         Google:  {BETTER_AUTH_URL}/api/auth/callback/google\n' +
      '         GitHub:  {BETTER_AUTH_URL}/api/auth/callback/github\n',
    );
  }
}

/**
 * Create the initial admin account on first boot.
 * No-op if any user already exists in the database.
 */
export async function runBootstrap(): Promise<void> {
  validateStartupConfig();

  const [existingUser] = await db.select({ id: authUser.id }).from(authUser).limit(1);
  if (existingUser) return;

  const email = (process.env.INITIAL_ADMIN_EMAIL || 'admin@localhost').trim().toLowerCase();
  const providedPassword = process.env.INITIAL_ADMIN_PASSWORD?.trim();
  const autoGenerated = !providedPassword;
  const password = providedPassword || randomBytes(12).toString('base64url');

  const userId = randomBytes(16).toString('hex');
  const agentId = userId;
  const hashedPassword = await hashAuthPassword(password);
  const agentKeyRaw = randomBytes(32).toString('hex');
  const agentKeyHash = hashKey(agentKeyRaw);

  await db.transaction(async tx => {
    await tx.insert(authUser).values({
      id: userId,
      name: 'Admin',
      email,
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // BetterAuth credential account for email+password sign-in
    await tx.insert(authAccount).values({
      id: randomBytes(16).toString('hex'),
      accountId: userId,
      providerId: 'credential',
      userId,
      password: hashedPassword,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    await tx.insert(appUsers).values({
      userId,
      platformAdmin: true,
      createdAt: new Date(),
    });

    await tx.insert(agents).values({
      id: agentId,
      apiKeyHash: agentKeyHash,
      role: 'admin',
      authUserId: userId,
      balance: 0,
      createdAt: new Date(),
      approvedAt: new Date(),
    });

    await tx.insert(agentApiKeys).values({
      hash: agentKeyHash,
      agentId,
      workspaceId: 'default',
    });
  });

  const line = '═'.repeat(62);
  const pad = (s: string) => s.padEnd(60);
  const rows = [
    `╔${line}╗`,
    `║  ${pad('TELARCHY — FIRST BOOT COMPLETE')}  ║`,
    `╠${line}╣`,
    `║  ${pad(`Email:    ${email}`)}  ║`,
    ...(autoGenerated
      ? [
          `║  ${pad(`Password: ${password}`)}  ║`,
          `║  ${pad('')}  ║`,
          `║  ${pad('Auto-generated password — save it now.')}  ║`,
          `║  ${pad('Set INITIAL_ADMIN_PASSWORD in your env to')}  ║`,
          `║  ${pad('pre-configure it on future installs.')}  ║`,
        ]
      : [`║  ${pad('Password: (set via INITIAL_ADMIN_PASSWORD)')}  ║`]),
    `╚${line}╝`,
  ];
  console.log('\n' + rows.join('\n') + '\n');
}
