// GENERATED by scripts/build-vision.mjs from docs/data-room/vision.md. Do not edit;
// edit the markdown and run `node scripts/build-vision.mjs` (npm run build does).

export interface Vision {
  title: string;
  /** YYYY-MM-DD: the day the markdown last changed (its last commit's author
   *  date, or the build day when that is not known). */
  updatedAt: string;
  markdown: string;
}

export const VISION: Vision = {
  title: "Vision",
  updatedAt: "2026-09-11",
  markdown: "Not written yet.",
};
