import { type AskTurn, askAboutWorkspace } from '../lib/ask';
import { type HandoffState, renderHandoff } from '../lib/setup-handoff-fallback';
import { type DecisionId, renderSpec, sanitiseDecisionIds } from '../lib/setup-spec';
import type { Checklist } from './setup-checklist';

/**
 * The handoff, written by Otto (owner direction 2026-08-23: "i want the prompt
 * to be generated by the agent.. based off of specifications.. this way the
 * prompt can be a lot more personalized and accurate").
 *
 * It was assembled from a template until then, which made it correct and
 * useless: a template cannot know that this operator reads their number off a
 * subgraph, that they already run two floors, or that the only thing still
 * undecided is how contract markets get funded. Otto has read the whole
 * conversation, so he can write the version their own agent can act on.
 *
 * The reason a model may write it at all is that it does not have to be
 * trusted about anything checkable:
 *
 *  - Every id, slug and address is given to him in a FACTS block that this
 *    file builds from the database, and `guardFacts` rejects the result if he
 *    used any id-shaped token that is not in it. A wrong workspace id in a
 *    prompt is not a typo, it is an instruction to an agent that will act on
 *    it.
 *  - If he returns junk, or the guard fires, the deterministic template
 *    answers instead (`setup-handoff-fallback.ts`). The page always has a
 *    prompt; it is only sometimes the personalised one.
 *  - He is told to make the FIRST instruction "call GET /api/setup/checklist",
 *    so the agent on the other side verifies the state itself rather than
 *    trusting prose that may be an hour old.
 */

const HANDOFF_SYSTEM = `You write a single prompt that one person will paste into their own coding agent (Claude Code, Cursor, Codex, or similar) so that agent can finish setting up their Telarchy market.

You are not talking to the operator here. You are writing instructions addressed to their agent, in the operator's voice, as if they typed it. Second person: "I run X. Here is where we got to. Finish it."

What makes this prompt good:
- It is specific to THIS conversation. Name their organisation, their number, the source it is read from, the ceiling and the month, in their words. A prompt that would fit anyone is a failure.
- It says what is already true and what is left, using the checklist you are given, and it does not invent progress.
- It tells the agent the exact calls for what is left, with the real ids from the FACTS block.
- It is honest about what is NOT decided yet, and asks the agent to settle those with the operator rather than guessing. The specification below is the list of things that have to be decided.
- It ends with the standing rule: confirm with me before anything that spends credits or publishes.

Hard rules:
- Use ONLY ids, slugs, workspace names and URLs that appear in the FACTS block. If a fact is not there, say what is missing instead of inventing it. Never write a placeholder like <workspace-id>: either the real one, or a sentence telling the agent to look it up.
- The first instruction in the prompt is always to call the checklist and work from what it says is open. When a market exists: GET https://telarchy.com/api/setup/checklist?workspaceId= followed by the real id or slug. When none exists yet: GET https://telarchy.com/api/setup/checklist with no query at all, which answers with the specification, and then say that the market has to be created first.
- Plain text. No markdown headings, no bold, no bullet characters other than "-" at the start of a line. It is going into a text box.
- Never an em dash or an en dash.
- 200 to 320 words. Long enough to carry the decisions, short enough to paste.

Answer in exactly this shape and nothing else. No JSON, no code fence:

SETTLED: comma separated decision ids that this conversation has actually decided
OPEN: comma separated decision ids still to decide
PROMPT:
the prompt text, over as many lines as it needs`;

export interface HandoffInput {
  turns: AskTurn[];
  state: HandoffState;
  checklist: Checklist | null;
  /** What the client believed was settled before this turn, already
   *  sanitised. Only used as a hint; the model re-reads the conversation. */
  previouslySettled: DecisionId[];
}

export interface HandoffResult {
  prompt: string;
  settled: DecisionId[];
  open: DecisionId[];
  /** True when the model's version was used. False means the template
   *  answered, which is a real outcome worth showing in logs. */
  written: boolean;
}

/** The facts the model may use. Everything here comes from the database or
 *  from the request, never from anything anyone typed at Otto. */
export function renderFacts(state: HandoffState, checklist: Checklist | null): string {
  const lines: string[] = ['FACTS. These are true. Nothing outside this block may be quoted as an id or an address.'];
  lines.push(
    state.signedIn
      ? '- The operator is signed in on telarchy.com, so calls made with their session or their agent key run as them.'
      : '- The operator is NOT signed in and nothing has been created. They need an account at https://telarchy.com/signup, or a participant key from POST /api/agents/register.',
  );
  for (const w of state.opened) {
    lines.push(
      `- Market opened during this conversation: name "${w.name}", workspace id ${w.id ?? 'unknown'}, address https://telarchy.com/${w.slug}`,
    );
  }
  for (const w of state.workspaces.filter(w => !state.opened.some(o => o.slug === w.slug))) {
    lines.push(
      `- Market they already run: name "${w.name}", workspace id ${w.id ?? 'unknown'}, address https://telarchy.com/${w.slug}`,
    );
  }
  if (!state.workspaces.length) lines.push('- They run no market yet, so no workspace id exists.');
  if (checklist) {
    lines.push('- Checklist for that market, read from the database just now:');
    for (const item of checklist.items) {
      lines.push(`  - ${item.id} (${item.status}): ${item.note}`);
    }
    for (const b of checklist.blocking) lines.push(`  - BLOCKING: ${b}`);
  }
  lines.push('- The API base is https://telarchy.com/api and GET /api/help is the live endpoint catalog.');
  return lines.join('\n');
}

/** Anything shaped like an id we hand out: a uuid, or one of our short ids. */
const ID_SHAPED =
  /\b(?:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|ws-[a-z0-9-]{3,}|agent-[a-z0-9-]{3,}|metric-[a-z0-9-]{3,})\b/gi;
/** A telarchy.com market address. */
const FLOOR_URL = /telarchy\.com\/([a-z0-9][a-z0-9-]{1,})/gi;

/** Paths that are addresses on telarchy.com but not markets, so a prompt
 *  naming them is not claiming a workspace exists. */
const NON_FLOOR_PATHS = new Set([
  'api',
  'signup',
  'login',
  'manage',
  'season',
  'leaderboard',
  'marketplace',
  'about',
  'contact',
  'terms',
  'privacy',
  'legal',
  'data-room',
  'admin',
]);

/**
 * Refuse a prompt that names something we did not give it. The failure this
 * catches is specific and expensive: an agent handed a plausible-looking
 * workspace id will call the API with it and act on whatever comes back.
 */
export function guardFacts(prompt: string, facts: string): string | null {
  const allowedIds = new Set((facts.match(ID_SHAPED) ?? []).map(s => s.toLowerCase()));
  for (const found of prompt.match(ID_SHAPED) ?? []) {
    if (!allowedIds.has(found.toLowerCase())) return `invented id ${found}`;
  }
  const allowedSlugs = new Set(Array.from(facts.matchAll(FLOOR_URL)).map(m => m[1].toLowerCase()));
  for (const m of prompt.matchAll(FLOOR_URL)) {
    const slug = m[1].toLowerCase();
    if (NON_FLOOR_PATHS.has(slug)) continue;
    if (!allowedSlugs.has(slug)) return `invented address telarchy.com/${slug}`;
  }
  if (/<[a-z-]+>/i.test(prompt)) return 'left a placeholder in the prompt';
  return null;
}

/**
 * Read the model's answer.
 *
 * The shape asked for is three labelled lines because the payload is
 * multi-line prose, and JSON is the wrong container for that: asked for JSON,
 * this model writes real newlines inside the string, which `JSON.parse`
 * rejects outright. That failure is invisible from the outside, because a
 * refused parse falls back to the template and the page still shows a prompt.
 * Both other shapes are read anyway, since a model that has been told one
 * format will sometimes produce another.
 */
export function parseHandoffAnswer(raw: string): { prompt: string; settled: unknown; open: unknown } {
  const text = raw
    .trim()
    .replace(/^```(?:json|text)?/i, '')
    .replace(/```$/, '')
    .trim();

  const ids = (line: string | undefined) =>
    (line ?? '')
      .split(',')
      .map(s => s.trim())
      .filter(Boolean);
  const settledLine = text.match(/^SETTLED:\s*(.*)$/im)?.[1];
  const openLine = text.match(/^OPEN:\s*(.*)$/im)?.[1];

  const marker = text.search(/^PROMPT:\s*$/im);
  if (marker >= 0) {
    const after = text.slice(marker).replace(/^PROMPT:\s*/im, '');
    return { prompt: after.trim(), settled: ids(settledLine), open: ids(openLine) };
  }

  // JSON anyway: repair the raw newlines inside string literals first, which
  // is the only reason it would not parse.
  if (text.startsWith('{')) {
    let repaired = '';
    let inString = false;
    let escaped = false;
    for (const ch of text) {
      if (escaped) {
        repaired += ch;
        escaped = false;
        continue;
      }
      if (ch === '\\') {
        repaired += ch;
        escaped = true;
        continue;
      }
      if (ch === '"') {
        inString = !inString;
        repaired += ch;
        continue;
      }
      if (inString && (ch === '\n' || ch === '\r' || ch === '\t')) {
        repaired += ch === '\n' ? '\\n' : ch === '\r' ? '\\r' : '\\t';
        continue;
      }
      repaired += ch;
    }
    try {
      const parsed = JSON.parse(repaired.slice(0, repaired.lastIndexOf('}') + 1)) as Record<string, unknown>;
      return {
        prompt: typeof parsed.prompt === 'string' ? parsed.prompt.trim() : '',
        settled: parsed.settled,
        open: parsed.open,
      };
    } catch {
      return { prompt: '', settled: [], open: [] };
    }
  }

  // Neither shape: if it is long enough to be the prompt itself, it is.
  return { prompt: text, settled: ids(settledLine), open: ids(openLine) };
}

export async function writeHandoff(input: HandoffInput): Promise<HandoffResult> {
  const facts = renderFacts(input.state, input.checklist);
  const fallback = (): HandoffResult => ({
    prompt: renderHandoff(input.turns, input.state),
    settled: input.previouslySettled,
    open: [],
    written: false,
  });

  const brief = [
    facts,
    '',
    'THE SPECIFICATION. Every one of these has to be decided before the market is worth anything.',
    '',
    renderSpec({ withApi: true }),
    '',
    'THE CONVERSATION so far, between the operator (Me) and Otto:',
    '',
    input.turns.map(t => `${t.role === 'user' ? 'Me' : 'Otto'}: ${t.content}`).join('\n\n'),
  ].join('\n');

  try {
    const { answer } = await askAboutWorkspace(
      brief,
      [{ role: 'user', content: 'Write the prompt for my own agent now, as JSON.' }],
      [],
      // A document, not a chat turn: at the chat default this model spends the
      // whole budget reasoning and returns empty content, which is what made
      // every handoff on beta fall back to the template on 2026-08-23.
      { system: HANDOFF_SYSTEM, maxTokens: 2400 },
    );
    const parsed = parseHandoffAnswer(answer);
    const prompt = parsed.prompt;
    if (!prompt || prompt.length < 200) {
      console.error('handoff: model returned no usable prompt');
      return fallback();
    }
    const bad = guardFacts(prompt, facts);
    if (bad) {
      console.error(`handoff: refused the model's prompt, ${bad}`);
      return fallback();
    }
    return {
      prompt,
      settled: sanitiseDecisionIds(parsed.settled),
      open: sanitiseDecisionIds(parsed.open),
      written: true,
    };
  } catch (e) {
    console.error('handoff: generation failed:', e);
    return fallback();
  }
}
