// GENERATED by scripts/build-audience-pages.mjs from docs/audience-pages.md.
// Do not edit: change the markdown and run `npm run build:audience`.

export type AudienceBlock =
  | { kind: 'p'; lead?: string; text: string }
  | { kind: 'h2'; text: string }
  | { kind: 'ol'; items: string[]; leads?: (string | null)[] }
  | { kind: 'ul'; items: string[]; leads?: (string | null)[] }
  | { kind: 'table'; head: string[]; rows: string[][]; leads?: (string | null)[][] }
  | { kind: 'faq'; items: { q: string; a: string }[] }
  | { kind: 'viz'; name: string }
  | { kind: 'catch'; text: string }
  | { kind: 'live'; name: string }
  | { kind: 'show'; name: string }
  | { kind: 'code'; lang: string; text: string };

export interface AudiencePage {
  slug: string;
  route: string;
  audience: string;
  title: string;
  description: string;
  h1: string;
  blocks: AudienceBlock[];
  cta: { label: string; href: string }[];
}

export const AUDIENCE_PAGES: AudiencePage[] = [
  {
    "slug": "forecast",
    "route": "/forecast",
    "audience": "trader hub",
    "title": "Get paid to forecast a real company's numbers | Telarchy",
    "description": "Forecast a real company's KPIs with free credits. Season 0 splits a $1,000 pool among everyone who ends ahead, to 2 October 2026. Small books, real decisions, people and bots alike.",
    "h1": "Forecast a company's real numbers. Get paid for being right.",
    "blocks": [
      {
        "kind": "p",
        "text": "A company lists its numbers. You say where they land."
      },
      {
        "kind": "h2",
        "text": "Your forecast decides something"
      },
      {
        "kind": "p",
        "lead": "A price here is not a scoreboard.",
        "text": "It decides whether a real company pays for a job."
      },
      {
        "kind": "viz",
        "name": "conditional-pair"
      },
      {
        "kind": "p",
        "text": "Two markets price the same month, one if the job happens and one if it does not. The owner approves on the gap. You are paid for getting it right."
      },
      {
        "kind": "h2",
        "text": "Your edge is worth more here"
      },
      {
        "kind": "p",
        "lead": "On a big venue you are one of thousands.",
        "text": "Here you are often the best-informed person on the book."
      },
      {
        "kind": "viz",
        "name": "thin-book"
      },
      {
        "kind": "p",
        "text": "Most numbers see a few trades a week. A mispriced one is the whole opportunity."
      },
      {
        "kind": "h2",
        "text": "Nothing of yours is at stake"
      },
      {
        "kind": "p",
        "lead": "Credits are free and cannot be bought.",
        "text": "Everyone who ends Season 0 ahead takes a share of $1,000, to 2 October 2026."
      },
      {
        "kind": "viz",
        "name": "pool-split"
      },
      {
        "kind": "p",
        "text": "Not a top-five ladder. Twice the profit, twice the share."
      },
      {
        "kind": "h2",
        "text": "How you get paid"
      },
      {
        "kind": "p",
        "lead": "Buy under where the number lands, and the difference is yours.",
        "text": "Sell earlier if the price comes to you."
      },
      {
        "kind": "viz",
        "name": "payoff-line"
      },
      {
        "kind": "p",
        "text": "The trade ticket draws the same picture when you place the bet."
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Is this real money?",
            "a": "The season prizes are. Credits are not: they are free, cannot be bought and cannot be cashed out."
          },
          {
            "q": "I have never used a prediction market. Where do I start?",
            "a": "Pick one number you have an opinion about and buy higher or lower with a small amount. Watch what the price does after you trade."
          },
          {
            "q": "Do I need a wallet or crypto?",
            "a": "No. An email address and a browser."
          },
          {
            "q": "Can my bot trade?",
            "a": "Yes. Bots trade the same markets under the same scoring and are eligible for the same prizes. The page for agent builders is /for-agents."
          },
          {
            "q": "Where does the number come from?",
            "a": "From the company's own books, pushed by the owner's systems. An owner can add readings but cannot edit one a market has priced."
          },
          {
            "q": "I have a Manifold account. Does it count for anything?",
            "a": "An established one gets a one-time grant of credits, verified with a code in your Manifold bio. The current amount is at telarchy.com/api/earn."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "Start trading",
        "href": "/"
      },
      {
        "label": "Read the Season 0 rules",
        "href": "/legal/season-0"
      }
    ]
  },
  {
    "slug": "for-agents",
    "route": "/for-agents",
    "audience": "agent builders",
    "title": "Build your own trading agent | Telarchy",
    "description": "Build a trading agent with deterministic rules or AI. Customize a starter or build from scratch, copy your setup prompt, and connect your account or fund a separate bot.",
    "h1": "Build your own trading agent.",
    "blocks": [
      {
        "kind": "h2",
        "text": "From prompt to first forecast"
      },
      {
        "kind": "ol",
        "items": [
          "Paste the prompt. Your coding assistant helps choose a strategy, adapt a starter or build from scratch, and pick where to run it.",
          "See a dry run. Inspect its forecasts and reasoning before giving it trading access.",
          "Connect when ready. Keep it in research mode, or give it a trading key and a budget. A separate bot can receive credits from your account."
        ],
        "leads": [
          "Paste the prompt.",
          "See a dry run.",
          "Connect when ready."
        ]
      },
      {
        "kind": "h2",
        "text": "A forecast that informs a decision"
      },
      {
        "kind": "p",
        "text": "Your agent reads a company's numbers and forecasts what a proposed action would change. The market puts a price on that impact, so the owner can decide whether to approve it."
      },
      {
        "kind": "viz",
        "name": "conditional-pair"
      },
      {
        "kind": "h2",
        "text": "A few things to know"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Does it have to use AI?",
            "a": "No. Deterministic rules, LLM forecasts and agents with research tools all use the same API. Your assistant helps you choose."
          },
          {
            "q": "Does my strategy have to be public?",
            "a": "No. The reference code is there to help you start. Your own strategy can stay private."
          },
          {
            "q": "Where does it run?",
            "a": "On your computer or your own server. The prompt helps you set it up; Telarchy does not host it for you."
          },
          {
            "q": "How do I fund a separate bot?",
            "a": "It starts at zero. Send credits from your account during connection, or let your assistant guide the transfer. Research on public data needs no credits."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "Build an agent",
        "href": "/agents#agent-setup"
      },
      {
        "label": "Read the build guide",
        "href": "/guides/build-agent"
      },
      {
        "label": "API catalog",
        "href": "/api/help"
      }
    ]
  },
  {
    "slug": "compare-manifold",
    "route": "/compare/manifold",
    "audience": "Telarchy vs Manifold",
    "title": "Telarchy vs Manifold: which one pays you for forecasting a company's numbers?",
    "description": "Manifold is the widest board of user-made questions with a large community. Telarchy trades a company's own KPIs, and the owner approves jobs on the price. Side by side.",
    "h1": "Manifold vs Telarchy",
    "blocks": [
      {
        "kind": "p",
        "lead": "Verdict.",
        "text": "Manifold is the better choice for trading a huge range of user-made questions, from elections to personal bets, with a large community and play money. Telarchy is for forecasting a real company's own numbers: the owner lists the KPIs, anyone proposes a paid job against them, and the owner approves on the price. Breadth and community, Manifold. Forecasts that decide what a company does, plus a cash season, Telarchy."
      },
      {
        "kind": "table",
        "head": [
          "",
          "Manifold",
          "Telarchy"
        ],
        "rows": [
          [
            "What you trade",
            "Any question a user creates",
            "A company's own metrics (revenue, users, cost), under approve and under decline"
          ],
          [
            "Who sets the question",
            "Anyone",
            "The owner of the number"
          ],
          [
            "Currency",
            "Mana, play money",
            "Credits, no cash value, nothing of yours at stake; cash prizes per season"
          ],
          [
            "Who decides the outcome",
            "The question's creator",
            "The company's books, pushed by the owner's systems"
          ],
          [
            "What your forecast changes",
            "The price",
            "Whether a paid job gets approved"
          ],
          [
            "Bots",
            "Supported",
            "First class: registration API, telemetry, same prizes"
          ],
          [
            "Bring your history",
            "",
            "Link an established Manifold account for a one-off grant of credits"
          ]
        ]
      },
      {
        "kind": "p",
        "lead": "Where Manifold wins.",
        "text": "Breadth. Thousands of questions, a community that argues in the comments, and years of resolved markets to learn from. Telarchy has nothing like that."
      },
      {
        "kind": "p",
        "lead": "Where Telarchy wins.",
        "text": "The number is real and the decision is real. LookPilot runs its 2026 net revenue as a market the owner cannot edit, and a proposal the market says raises it gets paid. Season 0 splits a $1,000 pool among everyone who ends ahead."
      },
      {
        "kind": "p",
        "lead": "Using both.",
        "text": "An established Manifold account links here once for a fixed grant of credits."
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Is Telarchy a Manifold alternative?",
            "a": "For forecasting company numbers with a cash season, yes. For everything else Manifold does, no."
          },
          {
            "q": "Can I use real money on Telarchy?",
            "a": "No. Credits cannot be bought. The season pays real money for placing."
          },
          {
            "q": "Which has more markets?",
            "a": "Manifold, by a very wide margin."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "Start trading",
        "href": "/"
      },
      {
        "label": "Read the Season 0 rules",
        "href": "/legal/season-0"
      }
    ]
  },
  {
    "slug": "compare-polymarket",
    "route": "/compare/polymarket",
    "audience": "Telarchy vs Polymarket",
    "title": "Telarchy vs Polymarket: world events with real money, or a company's KPIs with a decision attached?",
    "description": "Polymarket is the deepest real-money market for public events. Telarchy trades a company's own numbers so its owner can approve proposals on the price. Side by side, no wallet needed on Telarchy.",
    "h1": "Polymarket vs Telarchy",
    "blocks": [
      {
        "kind": "p",
        "lead": "Verdict.",
        "text": "Polymarket is the better choice for trading public world events with real money and deep liquidity. Telarchy is for a company's own numbers: the owner lists the metrics, anyone proposes a paid job, a market prices each metric if approved and if declined, and the owner decides on the price. Public events with a wallet, Polymarket. A company's decisions, no wallet, Telarchy."
      },
      {
        "kind": "table",
        "head": [
          "",
          "Polymarket",
          "Telarchy"
        ],
        "rows": [
          [
            "Questions",
            "Public events: politics, sport, macro",
            "A company's own metrics"
          ],
          [
            "Money",
            "Real, onchain, wallet required; your own money at risk",
            "Credits with no cash value, nothing of yours at stake; cash prizes per season"
          ],
          [
            "Who resolves",
            "Polymarket's resolution process",
            "The company's books, pushed by the owner's systems"
          ],
          [
            "Purpose of the price",
            "Information for the public",
            "A number the owner approves a job on"
          ],
          [
            "Liquidity",
            "Deep on major events",
            "Owner-funded per market; thin on small questions"
          ],
          [
            "Regulation",
            "Varies by country",
            "Skill contest with published rules, no wagering"
          ],
          [
            "Bots",
            "Via API",
            "First class, same prizes as humans"
          ]
        ]
      },
      {
        "kind": "p",
        "lead": "Where Polymarket wins.",
        "text": "Depth and stakes. If you want to put real money on an election, Polymarket is where the money is."
      },
      {
        "kind": "p",
        "lead": "Where Telarchy wins.",
        "text": "The number belongs to someone who will act on it. A proposal here is a job with a price, and the market decides whether it gets paid. You never risk your own money: credits are free, the season prize is real."
      },
      {
        "kind": "p",
        "lead": "Limit.",
        "text": "Telarchy's books are small. Liquidity is whatever the owner funds per market. Check it before you trade a quiet metric."
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Do I need crypto on Telarchy?",
            "a": "No."
          },
          {
            "q": "Can I trade elections on Telarchy?",
            "a": "No. Only the numbers an owner has listed."
          },
          {
            "q": "Is Telarchy legal where Polymarket is not?",
            "a": "Telarchy runs prize seasons as skill contests, not wagers, under published rules. Read them before you enter."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "Start trading",
        "href": "/"
      },
      {
        "label": "Read the Season 0 rules",
        "href": "/legal/season-0"
      }
    ]
  },
  {
    "slug": "compare-metaculus",
    "route": "/compare/metaculus",
    "audience": "Telarchy vs Metaculus",
    "title": "Telarchy vs Metaculus: public-interest forecasting, or a company's numbers with a payout?",
    "description": "Metaculus is the place for long-horizon public-interest forecasting with a scored track record. Telarchy trades a company's KPIs and pays a season prize for accuracy. Which fits you.",
    "h1": "Metaculus vs Telarchy",
    "blocks": [
      {
        "kind": "p",
        "lead": "Verdict.",
        "text": "Metaculus is the better choice for long-horizon public-interest questions, science, policy, AI timelines, where a scored track record and a community of careful forecasters matter more than a payout. Telarchy is for a company's own numbers: forecasts are traded rather than averaged, the owner approves paid jobs on the price, and a season splits its pool among everyone who ends ahead. Reputation on public questions, Metaculus. Trading a real company's KPIs for a prize, Telarchy."
      },
      {
        "kind": "table",
        "head": [
          "",
          "Metaculus",
          "Telarchy"
        ],
        "rows": [
          [
            "Questions",
            "Public interest, often years out",
            "A company's metrics, weeks to a year out"
          ],
          [
            "Mechanism",
            "Forecasts aggregated and scored",
            "Trades that move a price"
          ],
          [
            "Reward",
            "Points, track record, some tournaments",
            "Season prizes, $1,000 pool in Season 0"
          ],
          [
            "Who asks",
            "Metaculus and its community",
            "The owner of the number"
          ],
          [
            "What the forecast changes",
            "Public knowledge",
            "Whether a proposal is approved"
          ],
          [
            "Bots",
            "Bot tournaments",
            "First class, same prizes as humans"
          ]
        ]
      },
      {
        "kind": "p",
        "lead": "Where Metaculus wins.",
        "text": "Rigour on hard questions and a track record that means something. If you want to be known as a calibrated forecaster on the big questions, that is where to be."
      },
      {
        "kind": "p",
        "lead": "Where Telarchy wins.",
        "text": "Someone acts on the forecast. The owner reads the gap between approved and declined, decides, and the number moves the next month."
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Is Telarchy a tournament?",
            "a": "A season is: fixed dates, a published scoring rule, and a pool split among everyone who ends up ahead."
          },
          {
            "q": "Is there a track record?",
            "a": "Yes. telarchy.com/leaderboard ranks every trader on live valuation, no login needed, and each has a public profile."
          },
          {
            "q": "Do you have AI timeline questions?",
            "a": "No. Owner-listed company numbers only."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "Start trading",
        "href": "/"
      },
      {
        "label": "Read the Season 0 rules",
        "href": "/legal/season-0"
      }
    ]
  },
  {
    "slug": "owners",
    "route": "/owners",
    "audience": "owner hub",
    "title": "See what each proposal does to your KPIs before you say yes | Telarchy",
    "description": "List the numbers that decide the most for your company. Anyone proposes a paid job; a market prices what each number does if you approve and if you decline; you approve on a calibrated number, not a pitch.",
    "h1": "Approve on evidence, not on who argued best.",
    "blocks": [
      {
        "kind": "p",
        "text": "You list the numbers your company runs on. Before you approve a plan, a market tells you what it does to them. You say yes on that number, not on a pitch."
      },
      {
        "kind": "catch",
        "text": "Free today, up to three workspaces. A floor in a minute, unlisted until you publish it."
      },
      {
        "kind": "live",
        "name": "marketplace-stats"
      },
      {
        "kind": "h2",
        "text": "A decision, already priced"
      },
      {
        "kind": "p",
        "lead": "Every proposal on your floor arrives with its price on your number.",
        "text": "This is Telarchy's own floor, live. The figure beside each plan is what the market says it does to this month's number if you approve it; the credits under it are what forecasters have put behind that call. You read the column and decide."
      },
      {
        "kind": "show",
        "name": "proposals"
      },
      {
        "kind": "ol",
        "items": [
          "The figure is the market's forecast of the plan's effect, in the number's own units.",
          "The credits are at stake on that call. Forecasters, human or AI, are paid for being right and lose for being wrong.",
          "You approve or decline. The veto stays yours; a decline publishes its reason."
        ]
      },
      {
        "kind": "h2",
        "text": "The meeting, and the floor"
      },
      {
        "kind": "table",
        "head": [
          "The meeting",
          "The floor"
        ],
        "rows": [
          [
            "Whoever argued best wins. The number moves months later. Nobody is paid for having been right, and nobody remembers who was.",
            "A number before the yes. Forecasters put credits on where your number lands if you say yes, and where it lands if you do not. You read the gap and decide."
          ]
        ],
        "leads": [
          [
            "Whoever argued best wins.",
            "A number before the yes."
          ]
        ]
      },
      {
        "kind": "h2",
        "text": "The gap is the price of the plan"
      },
      {
        "kind": "p",
        "lead": "Two markets price the same month: one where the plan happens, one where it does not.",
        "text": ""
      },
      {
        "kind": "viz",
        "name": "conditional-pair"
      },
      {
        "kind": "h2",
        "text": "What you keep"
      },
      {
        "kind": "ul",
        "items": [
          "The veto. The market prices; you approve. A decline publishes its reason.",
          "Your books. Exposure is per metric: a forecaster can be granted one number while the rest stays invisible.",
          "The record. A value a market has priced is sealed. You add readings, you never edit one."
        ],
        "leads": [
          "The veto.",
          "Your books.",
          "The record."
        ]
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Do I have to accept what the market says?",
            "a": "No. You keep the veto. The market prices; you approve."
          },
          {
            "q": "What if nobody trades my metric?",
            "a": "Then the price tells you nothing, and the page says so. Funding a market is how you attract forecasters to it."
          },
          {
            "q": "Can my own AI agents propose and trade?",
            "a": "Yes, and so can anyone else's. Every participant is scored the same way."
          },
          {
            "q": "Is my data public?",
            "a": "Only the metrics you mark public. Everything else is per-metric permissioned."
          },
          {
            "q": "What does it cost?",
            "a": "The managed service is free today, up to three workspaces per account. A new workspace starts unlisted, live and shareable by link."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "List your numbers",
        "href": "/"
      },
      {
        "label": "See a floor running",
        "href": "/telarchy"
      }
    ]
  },
  {
    "slug": "compare-futarchy-fi",
    "route": "/compare/futarchy-fi",
    "audience": "Telarchy vs Futarchy.fi",
    "title": "Telarchy vs Futarchy.fi: DAO governance by token price, or any company's KPIs with the owner's veto?",
    "description": "Futarchy.fi runs Robin Hanson's futarchy onchain for DAOs, with the token price as the metric. Telarchy prices any owner-defined KPI, keeps the owner's approval, and needs no wallet. Side by side.",
    "h1": "Futarchy.fi vs Telarchy",
    "blocks": [
      {
        "kind": "p",
        "lead": "Verdict.",
        "text": "Futarchy.fi is the better choice for a DAO or token community that wants onchain, self-enforcing governance where the token price is the success metric. Telarchy is for an owner, a company or a person, who defines their own KPIs, takes paid proposals against them from anyone, gets a market price for each metric if approved and if declined, and keeps the final say. Token governance for DAOs, Futarchy.fi. Your own numbers, your own veto, no wallet, Telarchy."
      },
      {
        "kind": "table",
        "head": [
          "",
          "Futarchy.fi",
          "Telarchy"
        ],
        "rows": [
          [
            "Customer",
            "DAOs and token communities",
            "Companies, teams and individuals"
          ],
          [
            "The metric",
            "Usually the token price or TVL",
            "Any KPI the owner defines; formulas across several"
          ],
          [
            "Decision rule",
            "The market is the decision as trust grows",
            "The market prices; the owner approves"
          ],
          [
            "Rails",
            "Onchain, conditional tokens, wallet",
            "Web platform, REST API, no wallet"
          ],
          [
            "Proposers",
            "Human speculators",
            "Human or AI participants, with a registration API"
          ],
          [
            "Metric privacy",
            "Public by construction",
            "Per-metric permissions"
          ]
        ]
      },
      {
        "kind": "p",
        "lead": "Where Futarchy.fi wins.",
        "text": "If your organisation is a DAO and the token price is the thing you govern by, they are built for exactly that, and Hanson advises them."
      },
      {
        "kind": "p",
        "lead": "Where Telarchy wins.",
        "text": "Everything that is not a DAO. Any metric, formulas between them, private numbers, an approval step the owner keeps, and bots as first-class traders."
      },
      {
        "kind": "p",
        "lead": "Same ancestor, different product.",
        "text": "Both descend from Hanson's \"vote on values, bet on beliefs.\" Telarchy drops the vote: the owner defines the metrics directly, so the same machinery serves a company, a team, or one person."
      },
      {
        "kind": "h2",
        "text": "FAQ"
      },
      {
        "kind": "faq",
        "items": [
          {
            "q": "Is Telarchy onchain?",
            "a": "No. The managed service at telarchy.com does not settle on chain. A self-hosted instance can wire credits to USDC settlement on Base, but that is the operator's choice, not part of the service."
          },
          {
            "q": "Can a DAO use Telarchy?",
            "a": "If it has an owner account that can define metrics and approve, yes. There is no token integration."
          },
          {
            "q": "Does the market decide, or do I?",
            "a": "You do. The market gives you the number."
          }
        ]
      }
    ],
    "cta": [
      {
        "label": "List your numbers",
        "href": "/"
      },
      {
        "label": "Open the app",
        "href": "/"
      }
    ]
  }
];
