#!/usr/bin/env node
/**
 * Generate functions/src/content/vision.ts from docs/data-room/vision.md.
 *
 * The data room's Vision tab (docs/data-room.md, "Vision") is one markdown
 * document. It lives under docs/ (docs govern) and the backend gets a
 * generated module, the same way scripts/build-guides.mjs feeds the guides:
 * the runtime image contains only what tsc emits from functions/src. The
 * generated file is committed; functions/src/__tests__/vision-content.test.ts
 * fails when it is out of sync with the markdown, and `npm run build`
 * regenerates it.
 *
 * `updatedAt` is the day the file last changed: the author date of its last
 * git commit, unless the working copy differs from HEAD or git is not
 * available (the Docker build has no .git), in which case it is today. Day
 * precision on purpose: a commit made a minute after the module was
 * generated must not make the test disagree with the file.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(REPO, 'docs', 'data-room', 'vision.md');
const OUT = join(REPO, 'functions', 'src', 'content', 'vision.ts');

export function parseVision(text) {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!m) throw new Error('docs/data-room/vision.md: missing front matter');
  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  if (!meta.title) throw new Error('docs/data-room/vision.md: front matter lacks title');
  return { title: meta.title, markdown: text.slice(m[0].length).replace(/^\n+/, '').replace(/\n$/, '') };
}

/** YYYY-MM-DD of the last commit that touched the file, or today when the
 *  file is uncommitted, modified since, or git is not there. */
export function updatedAtFor(file) {
  const today = new Date().toISOString().slice(0, 10);
  try {
    const git = (...args) =>
      execFileSync('git', ['-C', REPO, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    const dirty = git('status', '--porcelain', '--', file).trim();
    if (dirty) return today;
    const date = git('log', '-1', '--format=%aI', '--', file).trim();
    return date ? date.slice(0, 10) : today;
  } catch {
    return today;
  }
}

export function render({ title, markdown, updatedAt }) {
  return `// GENERATED by scripts/build-vision.mjs from docs/data-room/vision.md. Do not edit;\n// edit the markdown and run \`node scripts/build-vision.mjs\` (npm run build does).\n\nexport interface Vision {\n  title: string;\n  /** YYYY-MM-DD: the day the markdown last changed (its last commit's author\n   *  date, or the build day when that is not known). */\n  updatedAt: string;\n  markdown: string;\n}\n\nexport const VISION: Vision = {\n  title: ${JSON.stringify(title)},\n  updatedAt: ${JSON.stringify(updatedAt)},\n  markdown: ${JSON.stringify(markdown)},\n};\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const parsed = parseVision(readFileSync(SRC, 'utf8'));
  writeFileSync(OUT, render({ ...parsed, updatedAt: updatedAtFor(SRC) }));
  console.log(`wrote the vision (${parsed.title}, ${parsed.markdown.length} chars) to functions/src/content/vision.ts`);
}
