#!/usr/bin/env node
/**
 * Generate functions/src/content/guides.ts from docs/guides/*.md.
 *
 * The guides served at GET /api/guides/:section are documentation, so they live
 * as markdown under docs/ (docs govern) and the backend gets a generated module,
 * the same way scripts/build-changelog.mjs feeds the data room. The generated
 * file is committed; functions/src/__tests__/guides-content.test.ts fails when it
 * is out of sync with the markdown, and `npm run build` regenerates it.
 *
 * Each file: a front-matter block (title, description, category, order) and the
 * markdown body. The section id is the file name.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(REPO, 'docs', 'guides');
const OUT = join(REPO, 'functions', 'src', 'content', 'guides.ts');

export function parseGuide(id, text) {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!m) throw new Error(`docs/guides/${id}.md: missing front matter`);
  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  for (const k of ['title', 'description', 'category', 'order']) {
    if (!(k in meta)) throw new Error(`docs/guides/${id}.md: front matter lacks ${k}`);
  }
  const content = text.slice(m[0].length).replace(/\n$/, '');
  return {
    id,
    title: meta.title,
    description: meta.description,
    category: meta.category,
    order: Number(meta.order),
    content,
  };
}

export function loadGuides() {
  return readdirSync(SRC)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .sort()
    .map(f => parseGuide(basename(f, '.md'), readFileSync(join(SRC, f), 'utf8')));
}

export function render(sections) {
  const body = sections
    .map(
      s =>
        `  {\n    id: ${JSON.stringify(s.id)},\n    title: ${JSON.stringify(s.title)},\n    description: ${JSON.stringify(s.description)},\n    category: ${JSON.stringify(s.category)},\n    order: ${s.order},\n    content: ${JSON.stringify(s.content)},\n  },`,
    )
    .join('\n');
  return `// GENERATED by scripts/build-guides.mjs from docs/guides/*.md. Do not edit;\n// edit the markdown and run \`node scripts/build-guides.mjs\` (npm run build does).\n\nexport interface GuideSection {\n  id: string;\n  title: string;\n  description: string;\n  category: string;\n  /** Position within the category. Lower = earlier. */\n  order: number;\n  content: string;\n}\n\nexport const GUIDE_SECTIONS: GuideSection[] = [\n${body}\n];\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sections = loadGuides();
  writeFileSync(OUT, render(sections));
  console.log(`wrote ${sections.length} guide sections to functions/src/content/guides.ts`);
}
